blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://ui.nuxt.com/
    about: Check the documentation for guides and examples.
  - name: #ï¸âƒ£ Discord
    url: https://discord.nuxtjs.org/
    about: Consider asking questions in the `#ui` channel.
